version: "3.9"

services:
  db:
    container_name: postgres-exchange
    image: postgres:14.4
    environment:
      POSTGRES_DB: "exchange"
      POSTGRES_USER: "exchange"
      POSTGRES_PASSWORD: "JzMggN1"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./exchange/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  work-exchange:
    build: .
    image: work/exchange:v1
    ports:
      - "8081:8081"
