server:
  port: 8082
grpc:
  port: 7777
  enable-reflection: true
security:
  basic:
    enabled: false
spring:
  application:
    name: exchange
  boot:
    admin:
      client:
        url: http://localhost:8080
  rabbitmq:
    port: 5672
    host: 'localhost'
    username: "root"
    password: "JzMggN"
  queue:
    name: queue-test
  datasource:
    driver-class-name: org.postgresql.Driver
    username: broker
    password: JzMggN
    url: jdbc:postgresql://localhost:5432/broker
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql
  sql:
    init:
      platform: postgres
      continue-on-error: true
      mode: never
logging:
  level:
    root: INFO
    com.deft: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always