server:
  port: 8082
grpc:
  port: 7777
  enable-reflection: true
security:
  basic:
    enabled: false
spring:
  application:
    name: exchange
  boot:
    admin:
      client:
        url: http://localhost:8080
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "exchange"
    password: "JzMggN1"
    url: jdbc:postgresql://localhost:5432/exchange
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database: postgresql
  sql:
    init:
      platform: postgres
      continue-on-error: true
      mode: never
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always